USE pokemons;

CREATE TABLE IF NOT EXISTS `pokemons` (
  `id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'id',
  `name` VARCHAR(25) NOT NULL COMMENT '名前',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ポケモン';

CREATE TABLE IF NOT EXISTS `types`(
  `id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'id',
  `name` VARCHAR(25) NOT NULL COMMENT '名前',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='タイプ';

CREATE TABLE IF NOT EXISTS `pokemon_types` (
  `id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'id',
  `pokemon_id` INT UNSIGNED NOT NULL COMMENT 'ポケモンid',
  `type_id` INT UNSIGNED NOT NULL COMMENT 'タイプid',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ポケモンのタイプ';
