version: '3.7'
services:
  mysql:
    image: mysql:8
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306